### ISSUE TITLE
Fletxes

### ISSUE THREAD

**Issue by JoniMega** [biels/Minicat#1]
Cada cop que dispares amb un arc, les fletxes surten des d'un angle determinat, independentment del angle en el que disparis (visualment), encara que en la realitat el llançament s'efectuï correctament no es pot determinar fàcilment si has disparat massa lluny o massa a prop ja que la fletxa sempre la veuràs en el mateix angle.

**Comment by biels** [comment]
Sembla ser un bug generalitzat.
https://bugs.mojang.com/browse/MC-417
Miraré què hi puc fer.

**Comment by biels** [comment]
Finalment, problema solucionat ;)
