### ISSUE TITLE
SpawnPoint

### ISSUE THREAD

**Issue by JoniMega** [biels/Minicat#11]
Els llocs de spawn del mode de joc Quakecraft careixen de protecció contra spawn-kill

**Comment by JoniMega** [comment]
Biel, encara et falta que donar un segon i mig de invencibilitat, hi han cops que un dispara al spawn més lluny  i que aquell torna a aparèixer a aquell mateix spawn ja que segueix sent el de més lluny. Així permets que hi hagi temps de reacció quan es espawneja. :)

**Comment by biels** [comment]
Si, també hauré de modificar la funció d'spawn òptim afegint un factor
aleatori per evitar que hi hagin spawns "morts"
