### ISSUE TITLE
Entrada a una partida

### ISSUE THREAD

**Issue by JoniMega** [biels/Minicat#15]
D'avegades un jugador és forçat a entrar a una partida abans que pugui fer /login

**Comment by biels** [comment]
No puc solucionar això perquè no disposo de l'API del plugin de login

**Comment by JoniMega** [comment]
doncs fes que els primers 6 segons al entrar al servidor, no et puguin invitar xP 
Pensa biel que sempre hi han maneres de solucionar aquests problemes.

**Comment by biels** [comment]
Bona idea!

**Comment by biels** [comment]
Possiblement solucioni això juntament amb la d'evitar convidar jugadors AFK
