### ISSUE TITLE
Greix acumulatiu

### ISSUE THREAD

**Issue by biels** [biels/Minicat#16]
El servidor es peta inexplicablement després d'un cert nombre de partides, cal inviestigar.

**Comment by JoniMega** [comment]
Encara no solucionat :P

**Comment by biels** [comment]
Ara està més solucionat però encada queda algun element residual que va augmentant la quantitat de greix

**Comment by biels** [comment]
Sembla ser que l'efecte s'ha reduït però que segueix present. Caldrà afegir un mecanisme provisional que automatitzi el procés de reinici.

**Comment by biels** [comment]
El servidor pot funcionar durant un llarg període de temps sense alentir-se. Tot i això, certs jocs no gestionen bé les desaparicions espontànies de jugadors per abandonament /l o desconnexió. En tot cas s'hauria d'obrir una issue per cada problema en concret.
