### ISSUE TITLE
Protecció contra torres enemigues a la base

### ISSUE THREAD

**Issue by JoniMega** [biels/Minicat#21]
Biel has de canviar la manera de protecció aquells que estana  la base, bàsicament que la torre s'autodestrueixi sola.
![2016-01-08_01 12 56](https://cloud.githubusercontent.com/assets/12009707/12186659/3bd00ff2-b5a5-11e5-81c3-9d697bb66db3.png)

i evitar el spam de xat

**Comment by biels** [comment]
Sloucionat, però es pot millorar la solució
