### ISSUE TITLE
Crash quakecraft al matar jugadors invencibles

### ISSUE THREAD

**Issue by biels** [biels/Minicat#26]
Pot estar relacionat amb la immortalitat o amb les aures

**Comment by biels** [comment]
Sembla haver-se solucionat

**Comment by JoniMega** [comment]
biel, estava relacionat amb l'habilitat creeper

**Comment by biels** [comment]
Habilitats al quakecraft? Segur? 😂

**Comment by JoniMega** [comment]
Em referia al estat invencible en que et veus tort :P

**Comment by biels** [comment]
Val, llavors es pot marcar com a resolt
