### ISSUE TITLE
Els espactadors no són amics dels jugadors de Quakecraft

### ISSUE THREAD

**Issue by lluiscab** [biels/Minicat#28]
Quan un espectador agafa la camara d'un jugador de Quakecraft, si aquest jugador mor, també mor el  espectador (Donant 2 punts, Double Kill a la persona que l'ha matat) Aixo també passa si el jugador que te a l'espectador a la seva camara dispara al bloc a on es, per tant, mata al espectador i guanya un punt.

**Comment by biels** [comment]
Potencial solució aplicada, falta comprovar

**Comment by biels** [comment]
Potencial solució aplicada de nou, falta comprovar
