### ISSUE TITLE
Torretes

### ISSUE THREAD

**Issue by JoniMega** [biels/Minicat#3]
En el joc de Torretes hi ha un Escarbat en que de vegades la torreta deixa de atacar i l'enemic pot travessar la última torreta que protegeix el nexe sense haver-la de destruir

![2015-10-09_17 16 29](https://cloud.githubusercontent.com/assets/12009707/10398827/5fcaa76a-6eaf-11e5-9966-5e981a1b1e28.png)

**Comment by biels** [comment]
Això era lag ¬¬ Tot i que és molt difícil entrar, les torres per si mateixes no ho impedeixen
