### ISSUE TITLE
Arquer màgic no funciona després de morir

### ISSUE THREAD

**Issue by biels** [biels/Minicat#32]
Aparentment el handler @ onEntityShootBow passa un craftplayer que canvia al morir, cal burcar una manera alternativa d'identificar el jugador

**Comment by biels** [comment]
És un poblema comú en totes les habilitats, falta determinar la causa

**Comment by JoniMega** [comment]
Tenim encara el Arquer màgic? o ja podriem tancar la issue?

**Comment by lluiscab** [comment]
@JoniMega en la majoria de jocs, les habilitats estan desactivades, potser s'hauria de mirar

**Comment by biels** [comment]
Cert, per la versió 2.0 hi hauran coses amb funcionalitat similar. Llavors ja mirarem si hi ha algun problema, però el més segur és que ho faci de nou.
