### ISSUE TITLE
Excés de Comands al xat

### ISSUE THREAD

**Issue by JoniMega** [biels/Minicat#4]
Bastants cops el servidor espameja informació innecessària al xat.
![2015-10-09_16 53 02](https://cloud.githubusercontent.com/assets/12009707/10398902/d7b59622-6eaf-11e5-932d-fe2017b025c8.png)

**Comment by biels** [comment]
S'han reduït alguns missatges al xat, encara no es dona per resolt

**Comment by biels** [comment]
Faltaria mirar si hi ha algun missatge innecessari encara, però en tot cas en una altra issue
