### ISSUE TITLE
slimes bugejats a rainbow clay!

### ISSUE THREAD

**Issue by Atm0n** [biels/Minicat#44]
doncs que entrem al pilota splash i quan acabem i sortim som slimes bugejats. opdem jugar a rainbow clay com a slimes!

**Comment by JoniMega** [comment]
![photo46360968370957642](https://cloud.githubusercontent.com/assets/12009707/13226980/9f595dc2-d994-11e5-98dd-88f897a7527b.jpg)

**Comment by biels** [comment]
Sembla ser un problema de la api, mentre no sàpiga com fer-ho, desactivare
els slimes

**Comment by biels** [comment]
Slimes desactivats, esperant una millora de la API
