### ISSUE TITLE
pilota splash!

### ISSUE THREAD

**Issue by Atm0n** [biels/Minicat#45]
quan mates a un usuari conta per 2, suposo que 1 és per l'user i l'altre per l'slime5(¿?)

**Comment by JoniMega** [comment]
Ull, que si hi ha algú en espectador observant la vista d'algú pot fer que el sistema es confongui, i conti que ha matat a dues persones.

**Comment by biels** [comment]
Els slimes han estat desactivats

**Comment by biels** [comment]
El problema de la mort d'espectadors hauria d'estar solucionat ara
