### ISSUE TITLE
[Proposta] Evitar spawnkill

### ISSUE THREAD

**Issue by lluiscab** [biels/Minicat#46]
Doncs bé, la meva proposta per a evitar el spawnkill és bastant simple, a tots els mapes hi ha un pre spawn, una base a on tu fas spawn, i a on nomes tu pots accedir, en aquesta base, hi ha un portal d'aigua que et fa tp a dos portals aleatoris al mapa (O més, aixi no pots campejar a un sol portal, no saps a quin sortira l'usuari). També s'eliminarien els efectes de ceguera i lentitud.

**Comment by JoniMega** [comment]
Lluis, els efectes de lentitud i ceguera són per fer que el jugador després de morir tingui una penalització de temps a la base. La lentitud li dona gairebé impossibilitat per moure's, i la ceguera perquè no pugui actuar amb fletxes des del spawn.

Respecte de fer un spawn on extern on no puguin ser atacats mentre estan en el temps de immobilització/morts, mmm no soluciona el spawnkill. Ja que els jugadors seguiran estant allí bloquejats, per exemple, intentant sortir del spawn de les torres que hi han davant.

no m'esplico molt bé ara, però t'asseguro que la proposta que has fet no soluciona el spawnkill, si vulguessis solucionar el problema del spawnkill seria que els jugadors puguessin sortir a través de diferentes sortides/spawns. En definitiva: que no hi hagi una única sortida.

**Comment by biels** [comment]
Afegir diversos punts d'spawn als jocs d'equip podria solucionar això. El problema és que la majoria de mapes tenen 1 sol spawn, cosa que caldria canviar per aplicar això. Bona suggerència (almeyys lap art que es reumeix en l'anterior) però difícil d'aplicar. En quin mapa és més exagerat aquest problema?

**Comment by JoniMega** [comment]
A torres de defensa i Quakecraft, principalment

**Comment by biels** [comment]
El mode de joc "torres de defensa" necessita un replantejament (obriré una issue a part), a quakecraft els spawns no funcionen d'aquesta manera.
