### ISSUE TITLE
Netejar Xat

### ISSUE THREAD

**Issue by JoniMega** [biels/Minicat#47]
Molts cops el xat es col·lapsat de missatges del sistema, i especialment quan acabes una partida, diguem-ne que quan vols veure la teva puntuació o posició del resultat, has de anar al xat i buscar-ho pel xat.
Estaria bé que el Xat, un cop comences una partida o acabes una partida es neteges lo suficient com per separar lo que és durant la partida i un cop acabat la partida. Bàsicament que no estigui com aquesta foto:
![2016-02-21_17 57 19](https://cloud.githubusercontent.com/assets/12009707/13267822/87f79234-da7f-11e5-9775-e28d8e1dbbb1.png)

**Comment by biels** [comment]
Cert, però quins missatges / tipus de missatges serien innecessaris?

**Comment by JoniMega** [comment]
Bàsicament, un cop que s'hagi acabat la partida hi hagi passat 2 segons que surti al xat això:

---Aqui comença el missatge del final de partida ----




//ho sé, molts espais





****************************************************
mr_comedi lluiscab VS JoniMega bielsr

FELICITATS HAS GUANYAT
ELO: +8
Kills: 7
*****************************************************
---Final del missatge----

**Comment by biels** [comment]
Val, ho faré en algun moment

**Comment by JoniMega** [comment]
Gairebé farà un any d'això? xD No sabia que fos complicat fer-ho. 
PD: Sé que és un pal, només us ho estic recordant...

**Comment by lluiscab** [comment]
Fet ;)
https://github.com/biels/Minicat/pull/75
