### ISSUE TITLE
PVP Amic

### ISSUE THREAD

**Issue by JoniMega** [biels/Minicat#5]
Actualment totes les partides tenen PVP amic, incoint les partides que no hi hauria d'haver pvp, no sé si és una novetat o si realment ha sigut un error del servidor

![2015-10-09_17 05 33](https://cloud.githubusercontent.com/assets/12009707/10398960/381f4832-6eb0-11e5-8909-37386b42141c.png)

**Comment by biels** [comment]
Aquest bug està solucionat, tot ia així queden les habilitats que si que afecten a aliats quan no haurien de fer-ho

**Comment by biels** [comment]
Solucionat
