### ISSUE TITLE
Arreglar ParkourFlow

### ISSUE THREAD

**Issue by JoniMega** [biels/Minicat#52]
El parkour segueix amb salts impossibles: :(
i també alguna cosa rara...

![2016-07-09_23 32 31](https://cloud.githubusercontent.com/assets/12009707/16710425/d4b2ea1e-462d-11e6-94f2-7adf07ef33cb.png)
![2016-07-09_23 32 46](https://cloud.githubusercontent.com/assets/12009707/16710426/d4b4fc5a-462d-11e6-9558-064a61163871.png)
![2016-07-09_23 32 57](https://cloud.githubusercontent.com/assets/12009707/16710427/d4b67684-462d-11e6-9b04-7f427a4afa4e.png)
![2016-07-09_23 33 15](https://cloud.githubusercontent.com/assets/12009707/16710428/d4bf80f8-462d-11e6-8906-7d4d6d0c6afc.png)

**Comment by lluiscab** [comment]
@JoniMega Teat

**Comment by biels** [comment]
- Primer salt buguejat
- La resta podriem dir que l'algoritme és millorable, però són salts possibles :)

**Comment by biels** [comment]
![image](https://cloud.githubusercontent.com/assets/5158960/16710464/99958002-462f-11e6-8d9f-bd7e7c674335.png)
La dist max és 4, per tant tos els salts haurien de ser possibles :S

**Comment by biels** [comment]
Planned to change spacing vector and make it bubble specific. This will allow to take the bubble design into account when calcualting the spacing vector. @amiguet3
