### ISSUE TITLE
Spleef

### ISSUE THREAD

**Issue by JoniMega** [biels/Minicat#6]
L'aparició del mode de joc Spleef, de vegades, apareixem en mig d'un bloc de gel provocant l'asfixia i la mort segura...
![2015-10-09_23 40 28](https://cloud.githubusercontent.com/assets/12009707/10407241/95a47198-6ee8-11e5-8242-d81d8fe4aa38.png)

**Comment by biels** [comment]
Aquest és d'aquells escarbats que ja formen part de la identitat de minicat

**Comment by JoniMega** [comment]
Biel, és un escarbat molest, i aquest s'ha de eliminar ja!

**Comment by biels** [comment]
Vols fer que minicat perdi la seva identitat nooo :'(

**Comment by JoniMega** [comment]
L'escarbat segueix present en forma de spawnejos que directament caus a sota. Solució: fer que l'spawn sigui +1 bloc de altura

**Comment by biels** [comment]
D'acord, solucionaré aquest escarbat

**Comment by biels** [comment]
Arreglat escarbat mític de minicat @JoniMega content? jajaja
