### ISSUE TITLE
Antic ParkourFlow

### ISSUE THREAD

**Issue by JoniMega** [biels/Minicat#74]
No és prioritari, però molta gent opina igual. El parkour actual no és divertit ni atractiu. I que estaria bé, almenys, tenir la opció de jugar al antic parkour, on només eren només blocs i disposats de forma sezilla :P 

Recordo que abans hi tot hi havia gent que jugava sola per intentar fer un rang alt i superar-se. Era divertit i satisfactori quan aconseguies una gran marca. 

Però jo ara sóc un usuari normal i esporàdic. Així que... m'agradaria tornar a minicat, no només pel rainbowclay, sinó perquè és un servidor de VARIS minijocs.

**Comment by biels** [comment]
D'acord, s'afegeix a la llista de coses per fer

**Comment by JoniMega** [comment]
Arreglat
