### ISSUE TITLE
ContenidorJoc.getMapCount() returns 0 for single map games.

### ISSUE THREAD

**Issue by lluiscab** [biels/Minicat#81]
**Expected result:**
ContenidorJoc.getMapCount() should return 1
**Actual result:**
ContenidorJoc.getMapCount() returns 0

See source: [Link](https://github.com/biels/Minicat/blob/106d79af9e0b83dbb06fbbe4ba280812f8752741/src/main/java/com/biel/lobby/GestorMapes.java#L221)

**Comment by biels** [comment]
Where is the problem then? Are you sure you are explaining it correctly?

**Comment by lluiscab** [comment]
See [getMultiWorldList](https://github.com/biels/Minicat/blob/ccfbf1f501c55bfb9c47e3e00fce8b150e237251/src/main/java/com/biel/lobby/mapes/MapaResetejable.java#L98) it returns an empty Array if the game MapMode is Single, which makes all single map games appear as they don't have any maps on the selector menu. Just wanted to open an issue as I just noticed this on the server and don't have time to fix this myself.

PS. Just noticed my typo on the first comment, it's now fixed.
